### ISSUE TITLE
hadoop-streaming dnloader is breaking because the mapper can't get the AWS credentials

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#35]
We are using hadoop streaming to manage the parallel dnloads of the data sets to S3.  In the process, we are instantiating a Luigi `S3Client` object which needs the AWS credentials.  As written, we try to get these values from the standard environment variables.  However, these environment variables are not available to the streaming mapper.

One solution is to set `-cmdenv` vars in the invocation of the streaming job.  However, it appears that Luigi does not support setting these options in `HadoopJobRunner`.  There are probably many workarounds, but the best would be to submit a Luigi patch that lets you set environment vars.

Thoughts, @tomwhite?  Is there a better way to get the AWS credentials to the mapper?

**Comment by tomwhite** [comment]
I think this is happening because AWS_ACCESS_KEY_ID is not set when using a non-interactive login shell (`ssh localhost 'echo $AWS_ACCESS_KEY_ID'` doesn't print a value).

One option would be to use the `hadoop` command for all S3 operations, since the S3 credentials are set in _/root/ephemeral-hdfs/conf/core-site.xml_. The problem would then reduce to https://github.com/bigdatagenomics/eggo/issues/34. The other nice thing about getting this to work is that we are not tied to S3, which may be useful - e.g. using eggo to populate files in HDFS.

**Comment by jfeala** [comment]
You may be able to get around this by appending the env vars to /etc/environment instead of ~/.bash_profile. This worked for me when SunGridEngine nodes were running in non-interactive mode

**Comment by tomwhite** [comment]
Thanks for the suggestion @jfeala. I was able to fix this in the end by specifying `-cmdenv` via the `streaming_args` parameter in Luigi. I committed this to unblock eggo and get master working again.

**Comment by laserson** [comment]
Awesome! For the record, I think the luigi S3 client either does or can
wrap the hadoop CLI.
